In [1]:
import numpy as np
import time

In [2]:
#execution performance 
size = 100_00_000

#time 

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")


#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 2.6950583457946777 seconds
numpy array time = 0.05213809013366699 seconds


In [3]:
#memory

import sys
print (f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print (f"python list size = {np_arr.nbytes} bytes")


python list size = 800000560000000 bytes
python list size = 80000000 bytes


In [4]:
# create -from lists 

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [5]:
#create 
arr1 = np.zeros((2, 3), dtype ="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((2, 3), dtype ="int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity metrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 10) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4 ) #linspace -evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


In [6]:
#properties 
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(arr.shape) #dimensions = m x n 
print(arr.size) #total elements= 9 
print(arr.dtype) #datatype
print(arr.ndim) #number of dimensions


float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [7]:
#operations on arrays
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)


flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [8]:
# indexing

#1D
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  #1
print(arr[3])  #4

1
4


In [9]:
#2D
arr1 = np.array([[1, 2, 3],[4, 5, 6]])

print(arr1[0][2])

3


In [10]:
#fancy indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [11]:
#boolean indexing 
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [12]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6])
#[start, end, step]

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])


[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 2 3 4 5 6]
[1 3 5]


In [13]:
#copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]

print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [14]:
#numpy array

arr =np.array([1, 2, 3, 4, 5])
sub_arr= arr[1:3].copy()
print(sub_arr)
   
sub_arr[0]=200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [15]:
#Datatype
arr =np.array([1, 2, 3, 4, 5])

arr = np.array(["prime", {1,2,3}, 3.14])
print(arr, arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [16]:
#Multidimentional Arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2 , 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [25]:
#3D array

arr3D = np.array([[[1, 2],[3, 4],[5, 6]],[[7, 8],[9, 10],[11, 12]]])

print(arr3D, arr3D.shape)

#indexing 
print(arr3D[1, 1, 0])


#slicing 
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first columns from both layers

arr3D[:, 0, :] = 99 

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [28]:
#vectorization

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr **2 )
print(arr + 10 )
print(arr + arr2 )

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [30]:
# broadcasting 

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr + arr2)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [38]:
#normalization

arr = np.array([[1, 2],[ 3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [42]:
#mathematical functions 

#aggregation 

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))

print(np.std(arr))
print(np.var(arr))
print(np.median(arr))

print(np.argmax(arr))
print(np.argmin(arr))

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
4
0


In [46]:
#Power Functions 

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [50]:
#log 

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [56]:
# rounding 

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1, 2, 3, 3, -6, 9, 6, -4, 5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-6 -4  1  2  3  5  6  9]
[-6 -4  1  2  3  3  5  6  9]
[1 2 3 3 6 9 6 4 5]
