In [2]:
import numpy as np
import time

In [3]:
#execution performance 
size = 100_00_000

#time 

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")


#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 2.436350107192993 seconds
numpy array time = 0.08627104759216309 seconds


In [4]:
#memory

import sys
print (f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print (f"python list size = {np_arr.nbytes} bytes")


python list size = 800000560000000 bytes
python list size = 80000000 bytes


In [5]:
# create -from lists 

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
#create 
arr1 = np.zeros((2, 3), dtype ="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((2, 3), dtype ="int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity metrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 10) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4 ) #linspace -evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


In [7]:
#properties 
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(arr.shape) #dimensions = m x n 
print(arr.size) #total elements= 9 
print(arr.dtype) #datatype
print(arr.ndim) #number of dimensions


float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#operations on arrays
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)


flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
# indexing

#1D
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  #1
print(arr[3])  #4

1
4


In [10]:
#2D
arr1 = np.array([[1, 2, 3],[4, 5, 6]])

print(arr1[0][2])

3


In [11]:
#fancy indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [12]:
#boolean indexing 
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [13]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6])
#[start, end, step]

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])


[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 2 3 4 5 6]
[1 3 5]


In [14]:
#copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]

print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [19]:
#numpy array

arr =np.array([1, 2, 3, 4, 5])
sub_arr= arr[1:3].copy()
print(sub_arr)
   
sub_arr[0]=200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [ ]:
#Datatype
arr =np.array([1, 2, 3, 4, 5])